services:
  lgdweb-hub:
    image: ghcr.io/tituxmetal/lgdweb-hub:prod
    container_name: lgdweb-hub
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000

networks:
  default-nw:
    external: true
  reverse-proxy-nw:
    external: true
